
services:
  vr_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vr-app-ct
    restart: always
    ports:
      - "5080:5000"
    networks:
      - vr_app_network
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/voice_recorder_app?authSource=admin
      - PORT=5000
    volumes:
      - ./client/dist:/app/client/dist
      - ./server:/app/server

networks:
  vr_app_network:
    external: true
    name: vr_app_network

volumes:
  bd-data: